### ISSUE TITLE
Make ESC or E also quit Inventory

### ISSUE THREAD

**Issue by ChromaPIE** [Blue-Beaker/backpack-opener#1]
First of all, great mod!

Yes you have to open your inventory first to do the right click so its current behavior is understandable. but I'd suggest at least having a config option or something that allows for quitting all the way from any GUI. because we are so used to scrolling to the item in hotbar and right click to open it, and pressing ESC gives the control of Steve right back to you without needing you to quit another GUI. so yeah its kinda inconvenient now.

**Comment by Blue-Beaker** [comment]
Added feature in 1.0.1. See mod config to find it.
